### ISSUE TITLE
Line of code exceeded 80 cols 

### ISSUE THREAD

**Issue by Intia-JoannaMarie** [PUP-BSIT/ex9-tech_nx#1]
@pepito-alonajane 
This line exceeded 80 columns according to the guideline:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/pepito_alonajane.html#L80

Kindly refer to this slide:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

Instead of this code:
![Screenshot 2024-04-16 010059](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146611304/4a2e68bc-77b4-4bb8-958f-a8e0a129ab6b)

Do this code instead:
![Screenshot 2024-04-16 005941](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146611304/84a2f9ee-3ef5-4ba8-8cbc-7c4514fbadd2)

**Comment by pepito-alonajane** [comment]
thank you
