### ISSUE TITLE
Separate CSS blocks with single space

### ISSUE THREAD

**Issue by Jalipa-Reanne-Rylle-C** [PUP-BSIT/ex9-tech_nx#10]
@Alimasa-Eliza 

There should be a single space between Line 115 and 116 for better readability.

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/alimasa_eliza/style.css#L111-L119

For Reference see the slide below:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR05Wa3VpfZeM514gTLpcL94wlCuIq2C-byTUcGazMqQaXGzLW28yakNGcI#slide=id.g24acb740da7_0_35

**Comment by ElizaAlimasa** [comment]
Thank you!
