### ISSUE TITLE
Suggestions regarding class names

### ISSUE THREAD

**Issue by Jalipa-Reanne-Rylle-C** [PUP-BSIT/ex9-tech_nx#11]
@Alimasa-Eliza 

It might be a good idea to use more specific class names to target elements. For example you can use "interests-lists", "works-list" instead of " li " so that you can easily identify which list is which, and this can reduce confusion in the future.

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/alimasa_eliza/alimasa_eliza.html#L38-L44

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/alimasa_eliza/alimasa_eliza.html#L26-L32

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/alimasa_eliza/alimasa_eliza.html#L51-L64

**Comment by ElizaAlimasa** [comment]
Thank you!
