### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Hassan-Adnan-T** [PUP-BSIT/ex9-tech_nx#12]
@Pasionpreciouskaye 

I assume that 'pasion_preciouskaye' file is your main HTML file, but it appears to have no content and no file extension (.html)

and that causes your netlify link not working.

if your intention is to use this html
'Pasion_preciouskaye_exer9.html'

you'd have to change this line 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/index.html#L21

and also 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pasion_preciouskaye/_redirects#L1

to 'Pasion_preciouskaye_exer9.html'

**Comment by Pasionpreciouskaye** [comment]
thankyou
