### ISSUE TITLE
Do not use <br> element

### ISSUE THREAD

**Issue by Hassan-Adnan-T** [PUP-BSIT/ex9-tech_nx#13]
@Pasionpreciouskaye 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pasion_preciouskaye/Pasion_preciouskaye_exer9.html#L44

refer to this coding guideline
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_139

**Comment by Pasionpreciouskaye** [comment]
thankyou
