### ISSUE TITLE
References different stylesheet

### ISSUE THREAD

**Issue by Hassan-Adnan-T** [PUP-BSIT/ex9-tech_nx#14]
@Pasionpreciouskaye 
there seems to be a discrepancy with your referenced CSS. 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pasion_preciouskaye/Pasion_preciouskaye_exer9.html#L7

you have a 'style.css' file, but you are referring to 'design.css'.

**Comment by Pasionpreciouskaye** [comment]
thankyou
