### ISSUE TITLE
Suggestion about blank files

### ISSUE THREAD

**Issue by Alejandro-AndreiJames** [PUP-BSIT/ex9-tech_nx#15]
@Tayoto-Mikaella 
This is not included in the slides of guidelines, yet, it is considered to be a bad practice since future code readers or even fellow coders might get confused on the blank files' purposes. Refer to the mentioned code files:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/exercise1.html
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/exercise2.html
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/exercise3.html
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/exercise4.html
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/exercise5.html

However, there are a few rare cases where it might be acceptable. If you plan to add content to the file in the future, you can leave a comment as a placeholder to indicate its intended purpose. 

You can simply put an html skeleton code and add comments such as "This is a filler", "Unfinished, will do soon" or a comment that notes the current / future purpose of the file. 

To automatically generate html skeleton code, you may do these to save time:
- Type "!" in the editor and hit enter. Refer to the image attached.
![434989990_7612272908888939_8736353056422695029_n](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/4e5017f1-5978-4189-9721-f6b092b96de8)

- It will automatically generate the html code skeleton.
![434877457_397114716519401_2064222510382549700_n](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/ba4d58ed-b54c-4d1c-89fe-5e589e9fb2fe)

Just a friendly advise :)

**Comment by Tayoto-Mikaella** [comment]
Thank you!
