### ISSUE TITLE
Proper naming convention

### ISSUE THREAD

**Issue by Alejandro-AndreiJames** [PUP-BSIT/ex9-tech_nx#16]
@Tayoto-Mikaella
Use proper naming conventions as given in the code guidelines in the highlighted codes given below:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/tayoto_mikaellaantonette.html#L6
 https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/tayoto_mikaellaantonette.html#L46
 
 
Classes should always be written in kebab-case, and IDs should be written in snake_case. Refer to this slide:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR2BWZgxviv6BSYUXPgFS2CtR2DAmj-WMdz21RIq9GIY9_3vqjyfBMxLAHQ#slide=id.g24da8de92d7_0_5

**Comment by Tayoto-Mikaella** [comment]
Thank you
