### ISSUE TITLE
Add a single space after the selector/s and before "{"

### ISSUE THREAD

**Issue by Alejandro-AndreiJames** [PUP-BSIT/ex9-tech_nx#17]
@Tayoto-Mikaella 
Kindly refer to this slide:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR2BWZgxviv6BSYUXPgFS2CtR2DAmj-WMdz21RIq9GIY9_3vqjyfBMxLAHQ#slide=id.g24acb740da7_0_35

Add a single space after the selector/s and before "{" in the mentioned css code lines below:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L1
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L12
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L18
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L22
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L27
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L32
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L36
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L42
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L46
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L51
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L62
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L69
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L80
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L91
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L99
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L105
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L111
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L115
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L119
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L123
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L127
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L131
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L135
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L139
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L143
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L148
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L156

**Comment by Tayoto-Mikaella** [comment]
Thank you!
