### ISSUE TITLE
Add a single space after the selector/s and before "{"

### ISSUE THREAD

**Issue by Hassan-Adnan-T** [PUP-BSIT/ex9-tech_nx#18]
@Pasionpreciouskaye 
Add a single space after the selector/s and before "{"
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pasion_preciouskaye/style.css#L1-L15

refer to this coding guidelines
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

**Comment by Pasionpreciouskaye** [comment]
thankyou
