### ISSUE TITLE
CSS code suggestion to avoid confusion

### ISSUE THREAD

**Issue by Alejandro-AndreiJames** [PUP-BSIT/ex9-tech_nx#19]
@Tayoto-Mikaella 
I kindly suggest that you put all the media queries in the css closely to each other to save time and avoid further confusions if you're already done on it or not. You may put all the media queries on the bottom part of the css codes to save time finding the lines where those are located. 

Refer to this highlighted line of codes:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L51C1-L68C1

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L156C1-L160C2

You may consider to do this instead for better readability. This version maintains the same functionality but reduces redundancy by combining the media queries that target the same elements and properties. Also, by keeping the media queries codes closely together, you will save time when finding where are the media queries are located. Refer to the image below: 
![image1](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/8d5e792c-8710-4e47-8f6c-1a39a5d0fee7)

**Comment by Tayoto-Mikaella** [comment]
Acknowledged, thank you!
