### ISSUE TITLE
Meta tag syntax error

### ISSUE THREAD

**Issue by Intia-JoannaMarie** [PUP-BSIT/ex9-tech_nx#2]
@pepito-alonajane 
There are syntax errors in the meta tag for the viewport:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/a1.html#L5
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/a2.html#L5
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/a3.html#L5
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/a4.html#L5
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/a5.html#L5

Refer to this code instead:
![435247068_449079397634509_8052892053405606683_n](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146611304/354783e0-13c0-4094-9980-98ddeeaee465)

As a code reviewer, I suggest that when creating a html code, you can simply type "!" and then, press enter to automatically generate html code skeleton. Kindly refer to the attached screenshots:
![434989990_7612272908888939_8736353056422695029_n](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146611304/2aad0925-2523-4e46-9114-1454103665b8)
![434877457_397114716519401_2064222510382549700_n](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146611304/2c8b6469-134e-44c0-a66d-9d3aeffe128c)

**Comment by pepito-alonajane** [comment]
thank you
