### ISSUE TITLE
Unnecessary/Unused CSS Codes

### ISSUE THREAD

**Issue by Alejandro-AndreiJames** [PUP-BSIT/ex9-tech_nx#20]
The mentioned CSS codes seems to be unused, you are calling classes that are not declared in your HTML code. Refer to the mentioned codes below:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L91C1-L97C2

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L139C1-L141C2

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/tayoto_mikaellaantonette/style.css#L143C33-L143C45

I kindly suggest to remove unnecessary codes since:
- When you have a lot of unused code, it can slow down build times and test execution.
- Unused code can introduce confusion and potentially lead to errors if someone accidentally interacts with it or mistakes it for active code.
- Version control systems track all changes made to the codebase.  Unused code adds unnecessary noise to the version history, making it harder to find relevant changes.

Here's a helpful analogy, imagine your repository as your workspace.  Keeping it clean and organized with only the tools and materials you need for your current project makes it easier to find what you're looking for and get things done.

It is also included in the guidelines that you should remove unnecessary files/codes in the repo:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR2BWZgxviv6BSYUXPgFS2CtR2DAmj-WMdz21RIq9GIY9_3vqjyfBMxLAHQ#slide=id.g25d18931cb7_3_0

**Comment by Tayoto-Mikaella** [comment]
Thank you.
