### ISSUE TITLE
Web Design Suggestions

### ISSUE THREAD

**Issue by Alejandro-AndreiJames** [PUP-BSIT/ex9-tech_nx#21]
@Tayoto-Mikaella 
- The background image overpowers the texts in terms of elements, and especially colors which may give difficulties in reading the texts from distance. You may want to use lesser element as a background to emphasize the text contents more and provide a better readability. Use colors the complements with the background color as well. You may refer to online resources of website's color palettes. 
![image](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/bf585680-177e-480e-a973-b0887d4234f8)

- The white spaces/ unused spaces in the sides are too much. You may want to make the text bigger to adjust to it, adjust the container's width and size.
![image](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/1e2389f6-0e45-4420-8c23-bd9a49411614)
![image](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/306dea19-1f1c-40a1-b3da-5f7b35a4a47c)

- Make the text contents bigger for a better readability and emphasis. The texts seems too small for the website design itself.
![image](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146566238/b9ed6612-fc63-4fee-a245-7e6604543e9d)

If you choose to modify the website and its content's color palette, you may check this site for suggestions:
https://colorhunt.co/

The suggestions that I gave are not in the guidelines. But, UI/UX wise, doing/ applying those principles will help you impress the website visitors/clients in your future works. Thank you and Good Luck to your future exercises! If you need help, kindly approach me for inquiries, I'll be glad to help you :)

**Comment by Tayoto-Mikaella** [comment]
This is noted, thank you for the information.
