### ISSUE TITLE
Unused css codes

### ISSUE THREAD

**Issue by Intia-JoannaMarie** [PUP-BSIT/ex9-tech_nx#5]
@pepito-alonajane 
These classes are not included in the HTML; therefore, they are not used in the CSS codes:
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/style.css#L36C1-L46C2
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/style.css#L94C1-L102C2

**Comment by pepito-alonajane** [comment]
thank you
