### ISSUE TITLE
Remove unnecessary lines

### ISSUE THREAD

**Issue by despe-reymondchristian** [PUP-BSIT/ex9-tech_nx#6]
@barrantes-sofiaanne 
Remove unnecessary spaces/lines: 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/barrantes_sofiaanne.html#L100
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/style.css#L256

Refer to this guideline: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1pphsWlliw0L_vbPJKbRCpW81Gt151vhOUq4iEw0Ftms7GjjedbKMX-fI_aem_AaHDPId1LpnIKTLO8jtJYQQGefS9ZBVU9dr1OCxS88dCO9DgcNB0UTMObNs4Ok6LM47wdHt4CyLzGnWZQJ0fiCb9#slide=id.g25d18931cb7_3_0

**Comment by barrantes-sofiaanne** [comment]
Thank you!
