### ISSUE TITLE
CSS improvement

### ISSUE THREAD

**Issue by Intia-JoannaMarie** [PUP-BSIT/ex9-tech_nx#7]
@pepito-alonajane 

https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/pepito_alonajane/style.css#L104C1-L104C55

For better readability, I suggest to use this as a reference:
![Screenshot 2024-04-16 015933](https://github.com/PUP-BSIT/ex9-tech_nx/assets/146611304/8a3b372b-6143-4580-a8c7-7c2b32dbcd0a)

**Comment by pepito-alonajane** [comment]
thank you
