### ISSUE TITLE
Lines of codes exceeded 80 columns

### ISSUE THREAD

**Issue by despe-reymondchristian** [PUP-BSIT/ex9-tech_nx#8]
@barrantes-sofiaanne 
Although it is a minor issue. Limit your line of codes to 80 columns. 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/barrantes_sofiaanne.html#L50C1-L66C13
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/barrantes_sofiaanne.html#L92

Refer to this coding guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1pphsWlliw0L_vbPJKbRCpW81Gt151vhOUq4iEw0Ftms7GjjedbKMX-fI_aem_AaHDPId1LpnIKTLO8jtJYQQGefS9ZBVU9dr1OCxS88dCO9DgcNB0UTMObNs4Ok6LM47wdHt4CyLzGnWZQJ0fiCb9#slide=id.g24da8de92d7_0_0

**Comment by barrantes-sofiaanne** [comment]
Thank you!
