### ISSUE TITLE
Remove unnecessary comments

### ISSUE THREAD

**Issue by despe-reymondchristian** [PUP-BSIT/ex9-tech_nx#9]
@barrantes-sofiaanne 

We suggest that you remove the unnecessary comments in your CSS. I suggested that you may only add comments when the line of code is more logical. 
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/style.css#L154C1-L167C2
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/style.css#L194C5-L206C6
https://github.com/PUP-BSIT/ex9-tech_nx/blob/897736ab85f8b91260d2e87fa3d55fe3ddb6f7f1/barrantes_sofiaanne/style.css#L222C1-L231C6

Refer to this coding guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1pphsWlliw0L_vbPJKbRCpW81Gt151vhOUq4iEw0Ftms7GjjedbKMX-fI_aem_AaHDPId1LpnIKTLO8jtJYQQGefS9ZBVU9dr1OCxS88dCO9DgcNB0UTMObNs4Ok6LM47wdHt4CyLzGnWZQJ0fiCb9#slide=id.g24da8de92d7_0_5

**Comment by barrantes-sofiaanne** [comment]
Thank You!
